[package]
name = "ta_experiments"
version = "0.1.0"
authors = ["Devin Gunay <devingunay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ta = "0.1.5"
alphavantage = { version = "0.6.0", features = ["blocking"] }
chrono = "0.4"
structopt = "0.3"
peroxide = { version = "0.25.2", features = ["dataframe"] }
# derive_more = { version = "0.6.2", features = ["display"] }
derive_more = "0.99"